/**
 * Documentation generator - creates .env.example and markdown docs from schema
 */

const fs = require('fs');
const path = require('path');

function generateEnvExample(schema, options = {}) {
  const lines = [
    '# Environment Variables',
    '# Generated by EnvGuard — do not edit manually',
    '# Run: npx envguard docs to regenerate',
    '',
  ];

  // Group by optional tags
  const required = [];
  const optional = [];

  for (const [key, rule] of Object.entries(schema)) {
    if (rule.required) {
      required.push([key, rule]);
    } else {
      optional.push([key, rule]);
    }
  }

  if (required.length > 0) {
    lines.push('# ── Required ──────────────────────────');
    for (const [key, rule] of required) {
      lines.push(...formatVarLine(key, rule));
    }
    lines.push('');
  }

  if (optional.length > 0) {
    lines.push('# ── Optional ──────────────────────────');
    for (const [key, rule] of optional) {
      lines.push(...formatVarLine(key, rule));
    }
    lines.push('');
  }

  return lines.join('\n');
}

function formatVarLine(key, rule) {
  const lines = [];
  const desc = rule.description || rule.desc || '';
  const type = rule.type || 'string';

  if (desc) {
    lines.push(`# ${desc}`);
  }

  let typeInfo = `type: ${type}`;
  if (rule.enum) typeInfo += `, allowed: ${rule.enum.join(' | ')}`;
  if (rule.min !== undefined) typeInfo += `, min: ${rule.min}`;
  if (rule.max !== undefined) typeInfo += `, max: ${rule.max}`;
  lines.push(`# ${typeInfo}`);

  if (rule.deprecated) {
    lines.push(`# ⚠ DEPRECATED${rule.replacement ? ` — use ${rule.replacement} instead` : ''}`);
  }

  const defaultVal = rule.default !== undefined ? rule.default : '';
  lines.push(`${key}=${defaultVal}`);
  lines.push('');

  return lines;
}

function generateMarkdownDoc(schema, options = {}) {
  const projectName = options.projectName || 'Project';
  const lines = [
    `# ${projectName} — Environment Variables`,
    '',
    '> Auto-generated by [EnvGuard](https://github.com/your-username/envguard)',
    '',
    '| Variable | Required | Type | Default | Description |',
    '|----------|----------|------|---------|-------------|',
  ];

  for (const [key, rule] of Object.entries(schema)) {
    const required = rule.required ? 'Yes' : 'No';
    const type = rule.type || 'string';
    const defaultVal = rule.default !== undefined ? `\`${rule.default}\`` : '—';
    let desc = rule.description || rule.desc || '';

    if (rule.enum) desc += ` (allowed: ${rule.enum.map((v) => `\`${v}\``).join(', ')})`;
    if (rule.deprecated) desc += ` ⚠ **Deprecated**${rule.replacement ? `, use \`${rule.replacement}\`` : ''}`;
    if (rule.min !== undefined) desc += ` (min: ${rule.min})`;
    if (rule.max !== undefined) desc += ` (max: ${rule.max})`;

    lines.push(`| \`${key}\` | ${required} | ${type} | ${defaultVal} | ${desc} |`);
  }

  lines.push('');
  return lines.join('\n');
}

function writeDocs(schema, outputDir, options = {}) {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write .env.example
  const exampleContent = generateEnvExample(schema, options);
  const examplePath = path.join(outputDir, '.env.example');
  fs.writeFileSync(examplePath, exampleContent, 'utf-8');

  // Write markdown doc
  const mdContent = generateMarkdownDoc(schema, options);
  const mdPath = path.join(outputDir, 'ENV.md');
  fs.writeFileSync(mdPath, mdContent, 'utf-8');

  return { examplePath, mdPath };
}

module.exports = { generateEnvExample, generateMarkdownDoc, writeDocs };
